### ISSUE TITLE
strconv.ParseInt: parsing "null": invalid syntax when calling datadog.NewClient(apiKey, appKey).GetMonitors()

### ISSUE THREAD

**Issue by DSh3p4rd** [zorkian/go-datadog-api#135] opened 2017-11-15 21:08 UTC
Sorry to be brief, I'm not getting back much insight to the problem from the error message. 

I've verified the api and app keys are correct and I'm using the latest version of the library pulled via go get github.com/zorkian/go-datadog-api

**Comment by ojongerius** [comment] 2017-11-22 09:45
@DSh3p4rd hey there, sorry for the long wait.

Would you be able to provide a config to reproduce this?

**Comment by gwellington** [comment] 2017-11-27 14:44
Hey @ojongerius I seem to be running into the same issue as well.  The configs that we had for a monitor were: 
```{
	"name": "some spiffy name",
	"type": "metric alert",
	"query": "min(last_5m):min:thisapp.health{app:someservice,type:monitor,stack:awesomestack} by {job} < 1",
	"message": "hey guys, fix this @some-team",
	"tags": [
		"app:sometag",
		"type:monitor",
		"somedashboard",
		"service:someservice",
		"service:anotherservice",
		"service:someservice.fqdn",
		"service:team"
	],
	"options": {
		"notify_audit": false,
		"locked": false,
		"timeout_h": 0,
		"new_host_delay": 300,
		"require_full_window": false,
		"notify_no_data": false,
		"renotify_interval": "0",
		"evaluation_delay": "",
		"escalation_message": "",
		"no_data_timeframe": null,
		"include_tags": false,
		"thresholds": {
			"critical": 1
		}
	}
}```

The config creates fine, but we started running into this issue when I changed the message of the monitor to notify another team.  Once the monitor was changed manually, the call to `GetMonitors` started breaking.  The only way to fix it was to delete the monitor and to let our systems programmatically recreate them again.

**Comment by ojongerius** [comment] 2017-11-28 09:39
Cheers @gwellington I might have some time this Friday, if anyone else is keen to pick this up, by all means go ahead 😄

**Comment by bluekeyes** [comment] 2017-11-30 21:26
It looks like this issue was _probably_ fixed by #129, which added a specific check for `null` before calling `strconv.ParseInt`. I'll try updating our project to use `master` instead of the last release and see if I can confirm.

**Comment by ojongerius** [comment] 2018-03-11 21:03
@bluekeyes any luck verifying?

**Comment by bluekeyes** [comment] 2018-03-11 21:33
Yes, updating to `master` back in November fixed the issue in our project, so this should be resolved in the latest releases.

**Comment by ojongerius** [comment] 2018-03-11 22:51
Thanks @bluekeyes !

**Closed by ojongerius** 2018-03-11 22:51 UTC
Labels: bug, help wanted
